import film01 from '../images/movies_thumbnails/pic__COLOR_pic.png';
import film02 from '../images/movies_thumbnails/pic__COLOR_pic-4.png';
import film03 from '../images/movies_thumbnails/pic__COLOR_pic-8.png';
import film04 from '../images/movies_thumbnails/pic__COLOR_pic-1.png';
import film05 from '../images/movies_thumbnails/pic__COLOR_pic-5.png';
import film06 from '../images/movies_thumbnails/pic__COLOR_pic-9.png';
import film07 from '../images/movies_thumbnails/pic__COLOR_pic-2.png';
import film08 from '../images/movies_thumbnails/pic__COLOR_pic-6.png';
import film09 from '../images/movies_thumbnails/pic__COLOR_pic-10.png';
import film10 from '../images/movies_thumbnails/pic__COLOR_pic-3.png';
import film11 from '../images/movies_thumbnails/pic__COLOR_pic-7.png';
import film12 from '../images/movies_thumbnails/pic__COLOR_pic-11.png';

export const DUMMY_DATA = [
  {
    _id: 'film01',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film01,
    owner: '',
    movieId: 0,
    nameRU: '33 слова о дизайне',
    nameEN: 'Английское название',
  },
  {
    _id: 'film02',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film02,
    owner: '777',
    movieId: 0,
    nameRU: 'Киноальманах «100 лет дизайна»',
    nameEN: 'Английское название',
  },
  {
    _id: 'film03',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film03,
    owner: '',
    movieId: 0,
    nameRU: 'В погоне за Бенкси',
    nameEN: 'Английское название',
  },
  {
    _id: 'film04',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film04,
    owner: '',
    movieId: 0,
    nameRU: 'Баския: Взрыв реальности',
    nameEN: 'Английское название',
  },
  {
    _id: 'film05',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film05,
    owner: '',
    movieId: 0,
    nameRU: 'Бег это свобода',
    nameEN: 'Английское название',
  },
  {
    _id: 'film06',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film06,
    owner: '777',
    movieId: 0,
    nameRU: 'Книготорговцы',
    nameEN: 'Английское название',
  },
  {
    _id: 'film07',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film07,
    owner: '',
    movieId: 0,
    nameRU: 'Когда я думаю о Германии ночью',
    nameEN: 'Английское название',
  },
  {
    _id: 'film08',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film08,
    owner: '',
    movieId: 0,
    nameRU: 'Gimme Danger: История Игги и The Stooges',
    nameEN: 'Английское название',
  },
  {
    _id: 'film09',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film09,
    owner: '',
    movieId: 0,
    nameRU: 'Дженис: Маленькая девочка грустит',
    nameEN: 'Английское название',
  },
  {
    _id: 'film10',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film10,
    owner: '',
    movieId: 0,
    nameRU: 'Соберись перед прыжком',
    nameEN: 'Английское название',
  },
  {
    _id: 'film11',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film11,
    owner: '',
    movieId: 0,
    nameRU: 'Пи Джей Харви: A dog called money',
    nameEN: 'Английское название',
  },
  {
    _id: 'film12',
    country: 'Россия',
    director: 'Михалков',
    duration: 77,
    year: '1999',
    description: 'Описание фильма',
    image: 'ссылка на изображение',
    trailerLink: 'ссылка на трейлер',
    thumbnail: film12,
    owner: '',
    movieId: 0,
    nameRU: 'По волнам: Искусство звука в кино',
    nameEN: 'Английское название',
  },
];
